#!/usr/bin/env node

'use strict';

global.__dirname__ = __dirname;

/**
* Module dependencies.
**/

const application = require('./lib/application');

/**
* Module body.
**/

global.app = application;
global.app.start();
