#!/usr/bin/env node

'use strict';

global.__dirname__ = __dirname;

/**
* Module dependencies.
**/

const Application = require('./lib/application');

/**
* Module body.
**/

global.app = new Application();
global.app.start();
